//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Drones')
export class DronesEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  Speed: number;

  @Column('text', { nullable: true })
  MotionAndDirection: string;

  @Column('text', { nullable: true })
  Status: string;
}
