//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('PlantDiseases')
export class PlantDiseasesEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  Name: string;

  @Column('text', { nullable: true })
  Type: string;

  @Column('text', { nullable: true })
  Symptoms: string;

  @Column('text', { nullable: true })
  ToxinType: string;

  @Column('text', { nullable: true })
  Effect: string;
}
