//Source code generated by AppGPT (www.appgpt.tech)
let data: any = {
  defaultData: {
    Drones: [
      {
        Speed: 1,
        MotionAndDirection: 'MotionAndDirection 1',
        Status: 'Status 1',
        id: 48,
      },
      {
        Speed: 2,
        MotionAndDirection: 'MotionAndDirection 2',
        Status: 'Status 2',
        id: 88,
      },
      {
        Speed: 3,
        MotionAndDirection: 'MotionAndDirection 3',
        Status: 'Status 3',
        id: 9,
      },
      {
        Speed: 4,
        MotionAndDirection: 'MotionAndDirection 4',
        Status: 'Status 4',
        id: 79,
      },
      {
        Speed: 5,
        MotionAndDirection: 'MotionAndDirection 5',
        Status: 'Status 5',
        id: 22,
      },
    ],
    PlantDiseases: [
      {
        Name: 'Name 1',
        Type: 'Type 1',
        Symptoms: 'Symptoms 1',
        ToxinType: 'ToxinType 1',
        Effect: 'Effect 1',
        id: 96,
      },
      {
        Name: 'Name 2',
        Type: 'Type 2',
        Symptoms: 'Symptoms 2',
        ToxinType: 'ToxinType 2',
        Effect: 'Effect 2',
        id: 87,
      },
      {
        Name: 'Name 3',
        Type: 'Type 3',
        Symptoms: 'Symptoms 3',
        ToxinType: 'ToxinType 3',
        Effect: 'Effect 3',
        id: 56,
      },
      {
        Name: 'Name 4',
        Type: 'Type 4',
        Symptoms: 'Symptoms 4',
        ToxinType: 'ToxinType 4',
        Effect: 'Effect 4',
        id: 20,
      },
      {
        Name: 'Name 5',
        Type: 'Type 5',
        Symptoms: 'Symptoms 5',
        ToxinType: 'ToxinType 5',
        Effect: 'Effect 5',
        id: 32,
      },
    ],
  },
};
export default data;
