//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

const enResources = {
  resources: {
    Drones: {
      name: 'Drones',
      fields: {
        Speed: 'Speed',
        MotionAndDirection: 'Motion And Direction',
        Status: 'Status',
        id: 'id',
      },
    },
    PlantDiseases: {
      name: 'Plant Diseases',
      fields: {
        Name: 'Name',
        Type: 'Type',
        Symptoms: 'Symptoms',
        ToxinType: 'Toxin Type',
        Effect: 'Effect',
        id: 'id',
      },
    },
  },
};
const frResources = {
  resources: {
    Drones: {
      name: 'Drones (fr)',
      fields: {
        Speed: 'Speed (fr)',
        MotionAndDirection: 'Motion And Direction (fr)',
        Status: 'Status (fr)',
        id: 'id',
      },
    },
    PlantDiseases: {
      name: 'Plant Diseases (fr)',
      fields: {
        Name: 'Name (fr)',
        Type: 'Type (fr)',
        Symptoms: 'Symptoms (fr)',
        ToxinType: 'Toxin Type (fr)',
        Effect: 'Effect (fr)',
        id: 'id',
      },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);

const translations = { en, fr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
  ],
);
